# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
docker: &docker_golang
  docker:
    - image: circleci/golang:1.9
  working_directory: /go/src/github.com/asicsdigital/does_it_redirect

version: 2
jobs:
  test:
    <<: *docker_golang

    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...

  build:
    <<: *docker_golang

    steps:
      - checkout

      # set up workspace
      - run: mkdir -p /tmp/workspace

      # gox for cross-compilation
      - run: go get github.com/mitchellh/gox
      - run: go get -v -t -d ./...
      - run: gox -osarch darwin/amd64 -osarch windows/amd64 -osarch windows/386 -osarch linux/amd64
      - run: cp does_it_redirect_* /tmp/workspace

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - does_it_redirect_darwin_amd64
            - does_it_redirect_windows_amd64
            - does_it_redirect_windows_386
            - does_it_redirect_linux_amd64

  release:
    <<: *docker_golang

    steps:
      - run: mkdir -p /artifacts
      - attach_workspace:
          at: /artifacts
      - store_artifacts:
          path: /artifacts

workflows:
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - build:
          requires:
            - test:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - release:
          requires:
            - build:
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

